version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "13:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build(deps/gha)"
    open-pull-requests-limit: 5
    labels:
      - dependencies
